[package]
name = "poke-engine"
version = "0.1.0"
authors = ["pmariglia <pmariglia@github.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = 1

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }

lazy_static = "1.4.0"
serde = { version = "1.0.197", features = ["derive"] }

[features]
gen_5_or_earlier_typechart = []
gen_6_or_later_typechart = []

gen4 = ["gen_5_or_earlier_typechart"]
gen5 = ["gen_5_or_earlier_typechart"]
gen6 = ["gen_6_or_later_typechart"]
gen7 = ["gen_6_or_later_typechart"]
gen8 = ["gen_6_or_later_typechart"]
gen9 = ["gen_6_or_later_typechart"]

default = ["gen9"]
